package export

import (
	"fmt"
	"io"
	"strings"
	"time"

	"github.com/pfrederiksen/cloudnecromancer/internal/engine"
)

// CDKExporter writes a Snapshot as an AWS CDK (TypeScript) stack.
type CDKExporter struct{}

// cdkConstructMapping maps internal type keys to CDK L2 construct info.
type cdkConstruct struct {
	Module    string // e.g. "aws-ec2"
	Class     string // e.g. "Instance"
	PropLines func(res engine.Resource) []string
}

var cdkConstructMapping = map[string]cdkConstruct{
	"ec2:instance": {
		Module: "aws-ec2",
		Class:  "CfnInstance",
		PropLines: func(res engine.Resource) []string {
			var lines []string
			if v, ok := res.Attributes["instanceType"].(string); ok {
				lines = append(lines, fmt.Sprintf("      instanceType: %q,", v))
			}
			if v, ok := res.Attributes["imageId"].(string); ok {
				lines = append(lines, fmt.Sprintf("      imageId: %q,", v))
			}
			if v, ok := res.Attributes["subnetId"].(string); ok {
				lines = append(lines, fmt.Sprintf("      subnetId: %q,", v))
			}
			return lines
		},
	},
	"ec2:vpc": {
		Module: "aws-ec2",
		Class:  "CfnVPC",
		PropLines: func(res engine.Resource) []string {
			var lines []string
			if v, ok := res.Attributes["cidrBlock"].(string); ok {
				lines = append(lines, fmt.Sprintf("      cidrBlock: %q,", v))
			}
			return lines
		},
	},
	"ec2:security_group": {
		Module: "aws-ec2",
		Class:  "CfnSecurityGroup",
		PropLines: func(res engine.Resource) []string {
			var lines []string
			if v, ok := res.Attributes["groupName"].(string); ok {
				lines = append(lines, fmt.Sprintf("      groupDescription: %q,", v))
			}
			if v, ok := res.Attributes["vpcId"].(string); ok {
				lines = append(lines, fmt.Sprintf("      vpcId: %q,", v))
			}
			return lines
		},
	},
	"s3:bucket": {
		Module: "aws-s3",
		Class:  "CfnBucket",
		PropLines: func(res engine.Resource) []string {
			var lines []string
			lines = append(lines, fmt.Sprintf("      bucketName: %q,", res.ResourceID))
			return lines
		},
	},
	"iam:role": {
		Module: "aws-iam",
		Class:  "CfnRole",
		PropLines: func(res engine.Resource) []string {
			return []string{
				fmt.Sprintf("      roleName: %q,", res.ResourceID),
				`      assumeRolePolicyDocument: {}, // TODO: reconstruct from CloudTrail`,
			}
		},
	},
	"lambda:function": {
		Module: "aws-lambda",
		Class:  "CfnFunction",
		PropLines: func(res engine.Resource) []string {
			var lines []string
			if v, ok := res.Attributes["functionName"].(string); ok {
				lines = append(lines, fmt.Sprintf("      functionName: %q,", v))
			}
			if v, ok := res.Attributes["runtime"].(string); ok {
				lines = append(lines, fmt.Sprintf("      runtime: %q,", v))
			}
			if v, ok := res.Attributes["handler"].(string); ok {
				lines = append(lines, fmt.Sprintf("      handler: %q,", v))
			}
			if v, ok := res.Attributes["role"].(string); ok {
				lines = append(lines, fmt.Sprintf("      role: %q,", v))
			}
			lines = append(lines, `      code: {}, // TODO: provide code location`)
			return lines
		},
	},
	"rds:db_instance": {
		Module: "aws-rds",
		Class:  "CfnDBInstance",
		PropLines: func(res engine.Resource) []string {
			var lines []string
			if v, ok := res.Attributes["engine"].(string); ok {
				lines = append(lines, fmt.Sprintf("      engine: %q,", v))
			}
			if v, ok := res.Attributes["dBInstanceClass"].(string); ok {
				lines = append(lines, fmt.Sprintf("      dbInstanceClass: %q,", v))
			}
			return lines
		},
	},
}

// Export writes the snapshot as a CDK TypeScript stack.
func (e *CDKExporter) Export(snapshot *engine.Snapshot, w io.Writer) error {
	// Collect required modules
	modules := make(map[string]bool)
	for typeKey := range snapshot.Resources {
		if c, ok := cdkConstructMapping[typeKey]; ok {
			modules[c.Module] = true
		}
	}

	// Header
	fmt.Fprintf(w, "// RECONSTRUCTED -- verify before deploying\n")
	fmt.Fprintf(w, "// Generated by CloudNecromancer at %s\n\n", snapshot.Timestamp.Format(time.RFC3339))
	fmt.Fprintf(w, "import * as cdk from 'aws-cdk-lib';\n")
	for mod := range modules {
		fmt.Fprintf(w, "import * as %s from 'aws-cdk-lib/%s';\n", cdkModuleAlias(mod), mod)
	}
	fmt.Fprintf(w, "import { Construct } from 'constructs';\n\n")

	// Stack class
	fmt.Fprintf(w, "export class CloudNecromancerStack extends cdk.Stack {\n")
	fmt.Fprintf(w, "  constructor(scope: Construct, id: string, props?: cdk.StackProps) {\n")
	fmt.Fprintf(w, "    super(scope, id, props);\n\n")

	for typeKey, resources := range snapshot.Resources {
		construct, known := cdkConstructMapping[typeKey]
		if !known {
			fmt.Fprintf(w, "    // Unsupported: %s (skipped)\n", sanitizeComment(typeKey))
			continue
		}

		alias := cdkModuleAlias(construct.Module)

		for _, res := range resources {
			varName := cdkVarName(res.ResourceID)
			fmt.Fprintf(w, "    new %s.%s(this, %q, {\n", alias, construct.Class, res.ResourceID)
			for _, line := range construct.PropLines(res) {
				fmt.Fprintf(w, "%s\n", line)
			}
			fmt.Fprintf(w, "    }); // %s\n\n", varName)
		}
	}

	fmt.Fprintf(w, "  }\n")
	fmt.Fprintf(w, "}\n")

	return nil
}

func cdkModuleAlias(module string) string {
	// "aws-ec2" → "ec2", "aws-s3" → "s3"
	parts := strings.SplitN(module, "-", 2)
	if len(parts) == 2 {
		return parts[1]
	}
	return module
}

func cdkVarName(resourceID string) string {
	return strings.Map(func(r rune) rune {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '_' {
			return r
		}
		return '_'
	}, resourceID)
}
