package export

import (
	"fmt"
	"io"
	"regexp"
	"strings"
	"time"

	"github.com/pfrederiksen/cloudnecromancer/internal/engine"
)

var safeHCLKey = regexp.MustCompile(`^[a-zA-Z_][a-zA-Z0-9_]*$`)

// HCLExporter writes a Snapshot as Terraform-importable HCL.
type HCLExporter struct{}

// resourceTypeMapping maps our internal type keys to Terraform resource types.
var resourceTypeMapping = map[string]string{
	"ec2:instance":         "aws_instance",
	"ec2:security_group":   "aws_security_group",
	"ec2:vpc":              "aws_vpc",
	"ec2:subnet":           "aws_subnet",
	"ec2:internet_gateway": "aws_internet_gateway",
	"iam:role":             "aws_iam_role",
	"iam:user":             "aws_iam_user",
	"iam:policy":           "aws_iam_policy",
	"s3:bucket":            "aws_s3_bucket",
	"lambda:function":      "aws_lambda_function",
	"rds:db_instance":      "aws_db_instance",
	"rds:db_cluster":       "aws_rds_cluster",
}

// hclAttributeMapping maps internal attribute names to Terraform argument names per resource type.
var hclAttributeMapping = map[string]map[string]string{
	"aws_instance": {
		"instanceType": "instance_type",
		"imageId":      "ami",
		"subnetId":     "subnet_id",
	},
	"aws_vpc": {
		"cidrBlock": "cidr_block",
	},
	"aws_subnet": {
		"vpcId":            "vpc_id",
		"cidrBlock":        "cidr_block",
		"availabilityZone": "availability_zone",
	},
	"aws_security_group": {
		"groupName": "name",
		"vpcId":     "vpc_id",
	},
	"aws_lambda_function": {
		"functionName": "function_name",
		"runtime":      "runtime",
		"handler":      "handler",
		"role":         "role",
	},
	"aws_db_instance": {
		"dBInstanceIdentifier": "identifier",
		"engine":               "engine",
		"dBInstanceClass":      "instance_class",
	},
}

// Export writes the snapshot as Terraform HCL with import blocks.
func (e *HCLExporter) Export(snapshot *engine.Snapshot, w io.Writer) error {
	fmt.Fprintf(w, "# RECONSTRUCTED -- verify before applying\n")
	fmt.Fprintf(w, "# Generated by CloudNecromancer at %s\n\n", snapshot.Timestamp.Format(time.RFC3339))

	for typeKey, resources := range snapshot.Resources {
		tfType, known := resourceTypeMapping[typeKey]
		for _, res := range resources {
			safeName := sanitizeTFName(res.ResourceID)

			if !known {
				// Unknown resource type -- sanitized to prevent comment-escape injection
				fmt.Fprintf(w, "# Unsupported resource type: %s\n", sanitizeComment(typeKey))
				fmt.Fprintf(w, "# resource_id: %s\n", sanitizeComment(res.ResourceID))
				fmt.Fprintf(w, "# attributes: (omitted for safety)\n\n")
				continue
			}

			// Import block
			fmt.Fprintf(w, "import {\n")
			fmt.Fprintf(w, "  to = %s.%s\n", tfType, safeName)
			fmt.Fprintf(w, "  id = %q\n", res.ResourceID)
			fmt.Fprintf(w, "}\n\n")

			// Resource block
			fmt.Fprintf(w, "resource %q %q {\n", tfType, safeName)
			attrMap := hclAttributeMapping[tfType]
			for internalKey, val := range res.Attributes {
				tfKey := internalKey
				if attrMap != nil {
					if mapped, ok := attrMap[internalKey]; ok {
						tfKey = mapped
					}
				}
				// Only emit attributes with safe HCL-compatible key names
				if !safeHCLKey.MatchString(tfKey) {
					continue
				}
				if s, ok := val.(string); ok {
					fmt.Fprintf(w, "  %s = %q\n", tfKey, s)
				}
			}
			fmt.Fprintf(w, "}\n\n")
		}
	}

	return nil
}

func sanitizeTFName(id string) string {
	// Strip all characters not valid in Terraform identifiers
	name := strings.Map(func(r rune) rune {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '_' {
			return r
		}
		return '_'
	}, id)
	// Terraform names must start with a letter or underscore
	if len(name) > 0 && name[0] >= '0' && name[0] <= '9' {
		name = "_" + name
	}
	if name == "" {
		name = "_unnamed"
	}
	return name
}

// sanitizeComment strips newlines and carriage returns from strings
// interpolated into code comments, preventing comment-escape injection.
func sanitizeComment(s string) string {
	r := strings.NewReplacer("\n", " ", "\r", " ")
	return r.Replace(s)
}
