package export

import (
	"fmt"
	"io"
	"strings"
	"time"

	"github.com/pfrederiksen/cloudnecromancer/internal/engine"
)

// PulumiExporter writes a Snapshot as a Pulumi (TypeScript) program.
type PulumiExporter struct{}

type pulumiResource struct {
	Package   string // e.g. "@pulumi/aws"
	Module    string // e.g. "ec2"
	Class     string // e.g. "Instance"
	PropLines func(res engine.Resource) []string
}

var pulumiMapping = map[string]pulumiResource{
	"ec2:instance": {
		Package: "@pulumi/aws", Module: "ec2", Class: "Instance",
		PropLines: func(res engine.Resource) []string {
			var lines []string
			if v, ok := res.Attributes["instanceType"].(string); ok {
				lines = append(lines, fmt.Sprintf("    instanceType: %q,", v))
			}
			if v, ok := res.Attributes["imageId"].(string); ok {
				lines = append(lines, fmt.Sprintf("    ami: %q,", v))
			}
			if v, ok := res.Attributes["subnetId"].(string); ok {
				lines = append(lines, fmt.Sprintf("    subnetId: %q,", v))
			}
			return lines
		},
	},
	"ec2:vpc": {
		Package: "@pulumi/aws", Module: "ec2", Class: "Vpc",
		PropLines: func(res engine.Resource) []string {
			var lines []string
			if v, ok := res.Attributes["cidrBlock"].(string); ok {
				lines = append(lines, fmt.Sprintf("    cidrBlock: %q,", v))
			}
			return lines
		},
	},
	"ec2:security_group": {
		Package: "@pulumi/aws", Module: "ec2", Class: "SecurityGroup",
		PropLines: func(res engine.Resource) []string {
			var lines []string
			if v, ok := res.Attributes["groupName"].(string); ok {
				lines = append(lines, fmt.Sprintf("    name: %q,", v))
			}
			if v, ok := res.Attributes["vpcId"].(string); ok {
				lines = append(lines, fmt.Sprintf("    vpcId: %q,", v))
			}
			return lines
		},
	},
	"s3:bucket": {
		Package: "@pulumi/aws", Module: "s3", Class: "Bucket",
		PropLines: func(res engine.Resource) []string {
			return []string{fmt.Sprintf("    bucket: %q,", res.ResourceID)}
		},
	},
	"iam:role": {
		Package: "@pulumi/aws", Module: "iam", Class: "Role",
		PropLines: func(res engine.Resource) []string {
			return []string{
				fmt.Sprintf("    name: %q,", res.ResourceID),
				`    assumeRolePolicy: "{}", // TODO: reconstruct from CloudTrail`,
			}
		},
	},
	"lambda:function": {
		Package: "@pulumi/aws", Module: "lambda", Class: "Function",
		PropLines: func(res engine.Resource) []string {
			var lines []string
			if v, ok := res.Attributes["functionName"].(string); ok {
				lines = append(lines, fmt.Sprintf("    name: %q,", v))
			}
			if v, ok := res.Attributes["runtime"].(string); ok {
				lines = append(lines, fmt.Sprintf("    runtime: %q,", v))
			}
			if v, ok := res.Attributes["handler"].(string); ok {
				lines = append(lines, fmt.Sprintf("    handler: %q,", v))
			}
			if v, ok := res.Attributes["role"].(string); ok {
				lines = append(lines, fmt.Sprintf("    role: %q,", v))
			}
			return lines
		},
	},
	"rds:db_instance": {
		Package: "@pulumi/aws", Module: "rds", Class: "Instance",
		PropLines: func(res engine.Resource) []string {
			var lines []string
			if v, ok := res.Attributes["engine"].(string); ok {
				lines = append(lines, fmt.Sprintf("    engine: %q,", v))
			}
			if v, ok := res.Attributes["dBInstanceClass"].(string); ok {
				lines = append(lines, fmt.Sprintf("    instanceClass: %q,", v))
			}
			return lines
		},
	},
}

// Export writes the snapshot as a Pulumi TypeScript program.
func (e *PulumiExporter) Export(snapshot *engine.Snapshot, w io.Writer) error {
	// Collect required modules
	modules := make(map[string]bool)
	for typeKey := range snapshot.Resources {
		if r, ok := pulumiMapping[typeKey]; ok {
			modules[r.Module] = true
		}
	}

	fmt.Fprintf(w, "// RECONSTRUCTED -- verify before deploying\n")
	fmt.Fprintf(w, "// Generated by CloudNecromancer at %s\n\n", snapshot.Timestamp.Format(time.RFC3339))
	fmt.Fprintf(w, "import * as aws from \"@pulumi/aws\";\n\n")

	for typeKey, resources := range snapshot.Resources {
		pr, known := pulumiMapping[typeKey]
		if !known {
			fmt.Fprintf(w, "// Unsupported: %s (skipped)\n", sanitizeComment(typeKey))
			continue
		}

		for _, res := range resources {
			varName := pulumiVarName(res.ResourceID)
			fmt.Fprintf(w, "const %s = new aws.%s.%s(%q, {\n", varName, pr.Module, pr.Class, res.ResourceID)
			for _, line := range pr.PropLines(res) {
				fmt.Fprintf(w, "%s\n", line)
			}
			fmt.Fprintf(w, "});\n\n")
		}
	}

	return nil
}

func pulumiVarName(resourceID string) string {
	name := strings.Map(func(r rune) rune {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '_' {
			return r
		}
		return '_'
	}, resourceID)
	// Ensure starts with letter
	if len(name) > 0 && name[0] >= '0' && name[0] <= '9' {
		name = "_" + name
	}
	return name
}
